server:
  port: 8681

spring:
  security:
    oauth2:
      client:
        registration:
           oauth2-demo-thymeleaf-client:
             client-id: oauth2-demo-thymeleaf-client
             client-secret: bb7d546c-dc82-4cc8-b25e-8902727b5a2b
             scope: openid, profile, roles
             authorization-grant-type: authorization_code
             redirect-uri: http://localhost:8681/login/oauth2/code/oauth2-demo-thymeleaf-client
        provider: 
           oauth2-demo-thymeleaf-client:
             issuer-uri: http://localhost:8581/auth/realms/oauth2-demo-realm
          